# Pin name action command file

# Start of element I2
ChangePinName(I2, 12, Black-)
ChangePinName(I2, 11, Red+)
ChangePinName(I2, 2, -)
ChangePinName(I2, 1, -)
ChangePinName(I2, 3, -)
ChangePinName(I2, 4, -)
ChangePinName(I2, 6, Black-)
ChangePinName(I2, 5, Red+)
ChangePinName(I2, 10, Red)
ChangePinName(I2, 9, Black)
ChangePinName(I2, 8, Green)
ChangePinName(I2, 7, Blue)
ChangePinName(I2, 15, NO)
ChangePinName(I2, 14, NC)
ChangePinName(I2, 13, C)
ChangePinName(I2, 18, Black-)
ChangePinName(I2, 17, Red+)
ChangePinName(I2, 16, "(PWM)")

# Start of element C2
ChangePinName(C2, 2, 2)
ChangePinName(C2, 1, 1)

# Start of element C1
ChangePinName(C1, 2, 2)
ChangePinName(C1, 1, 1)

# Start of element D2
ChangePinName(D2, 1, 1)
ChangePinName(D2, 2, 2)

# Start of element D1
ChangePinName(D1, 1, 1)
ChangePinName(D1, 2, 2)

# Start of element I1

# Start of element M3
ChangePinName(M3, 52, Vee)
ChangePinName(M3, 51, PWMd)
ChangePinName(M3, 44, PWMa)
ChangePinName(M3, 43, SigP)
ChangePinName(M3, 42, GND)
ChangePinName(M3, 41, Vext)
ChangePinName(M3, 40, Bm)
ChangePinName(M3, 39, Am)
ChangePinName(M3, 38, Ap)
ChangePinName(M3, 37, Bp)
ChangePinName(M3, 50, Vsys)
ChangePinName(M3, 49, Vee)
ChangePinName(M3, 48, PWMa)
ChangePinName(M3, 47, Vsys)
ChangePinName(M3, 46, GND)
ChangePinName(M3, 45, SigP)
ChangePinName(M3, 20, PWMd)
ChangePinName(M3, 19, PWMa)
ChangePinName(M3, 18, SigM)
ChangePinName(M3, 17, SigP)
ChangePinName(M3, 16, GND)
ChangePinName(M3, 15, SigAlt)
ChangePinName(M3, 13, GND)
ChangePinName(M3, 14, GND)
ChangePinName(M3, 12, Vext)
ChangePinName(M3, 11, Vext)
ChangePinName(M3, 9, Vee)
ChangePinName(M3, 10, Vee)
ChangePinName(M3, 8, Vsys)
ChangePinName(M3, 7, Vsys)
ChangePinName(M3, 6, +5V)
ChangePinName(M3, 5, Vee)
ChangePinName(M3, 4, Vsys)
ChangePinName(M3, 3, +3.3V)
ChangePinName(M3, 2, Vee)
ChangePinName(M3, 1, Vsys)

# Start of element M2
ChangePinName(M2, 52, Vee)
ChangePinName(M2, 51, PWMd)
ChangePinName(M2, 44, PWMa)
ChangePinName(M2, 43, SigP)
ChangePinName(M2, 42, GND)
ChangePinName(M2, 41, Vext)
ChangePinName(M2, 40, Bm)
ChangePinName(M2, 39, Am)
ChangePinName(M2, 38, Ap)
ChangePinName(M2, 37, Bp)
ChangePinName(M2, 50, Vsys)
ChangePinName(M2, 49, Vee)
ChangePinName(M2, 48, PWMa)
ChangePinName(M2, 47, Vsys)
ChangePinName(M2, 46, GND)
ChangePinName(M2, 45, SigP)
ChangePinName(M2, 20, PWMd)
ChangePinName(M2, 19, PWMa)
ChangePinName(M2, 18, SigM)
ChangePinName(M2, 17, SigP)
ChangePinName(M2, 16, GND)
ChangePinName(M2, 15, SigAlt)
ChangePinName(M2, 13, GND)
ChangePinName(M2, 14, GND)
ChangePinName(M2, 12, Vext)
ChangePinName(M2, 11, Vext)
ChangePinName(M2, 9, Vee)
ChangePinName(M2, 10, Vee)
ChangePinName(M2, 8, Vsys)
ChangePinName(M2, 7, Vsys)
ChangePinName(M2, 6, +5V)
ChangePinName(M2, 5, Vee)
ChangePinName(M2, 4, Vsys)
ChangePinName(M2, 3, +3.3V)
ChangePinName(M2, 2, Vee)
ChangePinName(M2, 1, Vsys)

# Start of element M1
ChangePinName(M1, 52, Vee)
ChangePinName(M1, 51, PWMd)
ChangePinName(M1, 44, PWMa)
ChangePinName(M1, 43, SigP)
ChangePinName(M1, 42, GND)
ChangePinName(M1, 41, Vext)
ChangePinName(M1, 40, Bm)
ChangePinName(M1, 39, Am)
ChangePinName(M1, 38, Ap)
ChangePinName(M1, 37, Bp)
ChangePinName(M1, 50, Vsys)
ChangePinName(M1, 49, Vee)
ChangePinName(M1, 48, PWMa)
ChangePinName(M1, 47, Vsys)
ChangePinName(M1, 46, GND)
ChangePinName(M1, 45, SigP)
ChangePinName(M1, 20, PWMd)
ChangePinName(M1, 19, PWMa)
ChangePinName(M1, 18, SigM)
ChangePinName(M1, 17, SigP)
ChangePinName(M1, 16, GND)
ChangePinName(M1, 15, SigAlt)
ChangePinName(M1, 13, GND)
ChangePinName(M1, 14, GND)
ChangePinName(M1, 12, Vext)
ChangePinName(M1, 11, Vext)
ChangePinName(M1, 9, Vee)
ChangePinName(M1, 10, Vee)
ChangePinName(M1, 8, Vsys)
ChangePinName(M1, 7, Vsys)
ChangePinName(M1, 80, Vee)
ChangePinName(M1, 78, Vee)
ChangePinName(M1, 76, Vee)
ChangePinName(M1, 75, Vsys)
ChangePinName(M1, 79, Vsys)
ChangePinName(M1, 77, Vsys)
ChangePinName(M1, 74, Vee)
ChangePinName(M1, 73, Vsys)
ChangePinName(M1, 6, +5V)
ChangePinName(M1, 5, Vee)
ChangePinName(M1, 4, Vsys)
ChangePinName(M1, 3, +3.3V)
ChangePinName(M1, 2, Vee)
ChangePinName(M1, 1, Vsys)
